plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.185'
}

repositories {

    maven {
        url = "https://maven.pkg.github.com/cccstudiocoder/Sky-core"
    }
    mavenCentral()

}

base {
    archivesName = "sky_core"
}

java{
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

runs {

    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', "sky_core"
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', "sky_core"
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', "sky_core"
    }

    data {
        arguments.addAll '--mod', "sky_core", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:21.1.179"
}

group = 'com.cccstudio'

version = '1.2.1'

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = 'com.cccstudio'
            artifactId = 'sky_core'
            version = '1.2.1'
        }
    }
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/cccstudiocoder/Sky-core')
            credentials {
                username = project.findProperty('gpr.user') ?: System.getenv('GPR_USER')
                password = project.findProperty('gpr.key') ?: System.getenv('GPR_KEY')
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
